### ISSUE TITLE
Since project is not supported, it may suggest to use ng-annotate-loader instead

### ISSUE THREAD

**Issue by huston007** [jeffling/ng-annotate-webpack-plugin#10]
https://github.com/huston007/ng-annotate-loader

**Comment by jeffling** [comment]
Added a note to the bottom. There are tradeoffs with loaders and plugins, so it's not a direct replacement.

**Comment by huston007** [comment]
@jeffling yeah, not direct replacement, but it can help in most use cases. Thank you.

**Comment by jeffling** [comment]
No problem :) Thanks for your work on the loader.
