### ISSUE TITLE
Add file exclude option

### ISSUE THREAD

**Issue by omichelsen** [jeffling/ng-annotate-webpack-plugin#13]
Is there any way to ensure that this does not run for libs in node_modules etc.?

**Comment by jeffling** [comment]
We could add an exclude option like in https://github.com/webpack/docs/wiki/list-of-plugins#uglifyjsplugin. 

Are you having trouble with it running for for node_modules?

**Comment by omichelsen** [comment]
Yes, I have no problems, but it accounts for around 25% of my total build time when I do a production build. Would really like to minimize the impact.

**Comment by jeffling** [comment]
That makes sense. I'm going to busy for the next few weekends, but I'm going to try to get to it. If anybody would like to submit a PR (it should be quite easy) I would be overjoyed :)

**Comment by omichelsen** [comment]
While trying to add this feature, it dawned on me that the plugin is working on the already bundled chunks. In that case it doesn't make much sense trying to include/exclude specific source files.

I therefore switched to the [ng-annotate-loader](https://github.com/huston007/ng-annotate-loader) instead, which seems to be a better fit for my use case.

Please enlighten me if I've misunderstood anything, and thanks for giving this consideration.

**Comment by jeffling** [comment]
You're probably right. I prefer a plugin because of our workflow, but if a loader works for you then you should use it instead. It's all the same.
