### ISSUE TITLE
New npm version ?

### ISSUE THREAD

**Issue by edi9999** [jeffling/ng-annotate-webpack-plugin#15]
Afaict, the version on npm is dated from 2 years ago, do you consider publishing a new version (https://www.npmjs.com/package/ng-annotate-webpack-plugin)

**Comment by aabenoja** [comment]
I have `$inject` annotations in my project that break on the old `0.9.11` of `ng-annotate` your "latest" release targets. An updated release (which include your nice version bumps to `ng-annotate` and `webpack-core`) would be greatly appreciated.

**Comment by jeffling** [comment]
Hey, I've done this. sorry about the delay.
