### ISSUE TITLE
Sourcemap a couple of lines off

### ISSUE THREAD

**Issue by cveld** [jeffling/ng-annotate-webpack-plugin#17]
I am experiencing that the generated sourcemap by Webpack is a few lines off compared to the source.  As soon as I disable your plugin, the lines are aligned again. Could it be related to issue #9? I am combining your plugin with TypeScript compilation.

**Comment by cveld** [comment]
I boldly moved away from your plug-in towards the ng-annotate-loader. This loader seems to work. Using the following Webpack config:
`loaders: [
          ...
          { test: /\.ts$/, loaders: ['ng-annotate', 'ts-loader'] },
          ...
}

**Comment by jeffling** [comment]
Thanks for reporting, cveld. I'll take a look this weekend and see what's wrong. 

I chose to use a plugin over a loader because the loader added more compilation time for a huge project, but if the loader works for you there is nothing wrong with it.

**Comment by dgsmith2** [comment]
I noticed this as well, but only when I use devtool value of 'source-map' or 'inline-source-map'.  The line numbers are correct if I use 'eval-source-map', however with this route it appears that breakpoints on the constructor and $onInit are not honored.

FWIW, I encounter the same issue with ng-annotate-loader

**Comment by jeffling** [comment]
That suggests that it's a problem with ng-annotate rather than something we can do - unfortunately this plugin only passes on sourcemaps blindly
