### ISSUE TITLE
Doesn't work with eval-cheap-source-map

### ISSUE THREAD

**Issue by jogjayr** [jeffling/ng-annotate-webpack-plugin#18]
The plugin worked fine when in my webpack conf I had:

```
devtool: 'source-map'
```

When I changed it to:

```
devtool: 'eval-cheap-source-map'
```

it stopped working and I got the strict DI violation error.

It's unlikely it's a problem with ng-annotate, because when I switched to ng-annotate-loader (while keeping ng-annotate unchanged), the issue was resolved.

Happy to provide other info if needed.

**Comment by cgatian** [comment]
I found that I needed to have the plugin first before any other plugins for it to work correctly.

```
config.plugins.splice(0, 0, new ngAnnotatePlugin({
		add: true
		// https://github.com/olov/ng-annotate
		// other ng-annotate options here
	}));
```

**Comment by jeffling** [comment]
@cgatian thank you for your message. this often is the reason why things don't work, since any other transformers make ng-annotate confused

**Comment by jogjayr** [comment]
Thanks for the quick replies @cgatian @jeffling 

I tried putting the ngAnnotatePlugin first in my webpack conf and it still doesn't work:

    plugins: [
      new ngAnnotatePlugin({
        add: true
      }),
      new ExtractTextPlugin('[name].css', {
        allChunks: true
      }),
      new HtmlWebpackPlugin({
        template: './src/index.html',
        inject: true
      }),
      new webpack.optimize.DedupePlugin(),
      new OptimizeCssAssetsPlugin({
        assetNameRegExp: /\.optimize\.css$/g,
        cssProcessor: require('cssnano'),
        cssProcessorOptions: { discardComments: { removeAll: true } },
        canPrint: true
      }),
      new webpack.ContextReplacementPlugin(/moment[\\\/]locale$/, /^\.\/(de|en|fr|ko|ja|zh-cn)$/)
    ],

**Comment by jeffling** [comment]
Could I see any other loaders you have for your source files?

**Comment by jogjayr** [comment]
Sure. Here's my loaders.js file (which I import into my conf file).

    var urlLoader = require.resolve('url-loader');
    var fileLoader = require.resolve('file-loader');

    var loaders = [
      {
        test: /\.ts(x?)$/,
        loader: 'ts-loader'
      },
      {
        test: /\.json$/,
        loader: 'json-loader'
      },
      {
        test: /(jquery)/,
        loader: 'script-loader'
      },
      {
        test: /(proj4)/,
        loader: 'script-loader'
      },
      {
        test: /(highcharts)/,
        loader: 'script-loader'
      },
      {
        test: /\.css$/,
        loader: 'style-loader!css-loader'
      },
      {
        test: /\.html$/,
        exclude: /node_modules/,
        loader: 'raw'
      },
      {
        test: /.*\.(gif)$/i,
        loaders: [
          'file?hash=sha512&digest=hex&name=[hash].[ext]',
          'image-webpack'
        ]
      },
      {
        test: /\.woff(2)?(\?v=[0-9]\.[0-9]\.[0-9])?$/,
        loader: urlLoader
      },
      {
        test: /\.svgico$/,
        loader: 'raw'
      },
      {
        test: /\.(ttf|eot|svg)(\?v=[0-9]\.[0-9]\.[0-9])?$/,
        loader: fileLoader
      },
      {
        test: '\.jpg$',
        exclude: /node_modules/,
        loader: 'file'
      },
      {
        test: '\.png$',
        exclude: /node_modules/,
        loader: 'url'
      }
    ];

    loaders.push({
      test: /\.scss$/,
      loader: 'style!css!resolve-url!sass?sourceMap'
    });


    module.exports = loaders;

**Comment by jogjayr** [comment]
I also have some preloaders:

    module.exports = [
      {
        test: /\.js$/,
        exclude: [/node_modules/, /dist/],
        loader: 'jshint-loader'
      },
      {
        test: /\.ts$/,
        exclude: /node_modules/,
        loader: 'tslint-loader'
      },
      {
        test: /\.scss$/,
        exclude: /node_modules/,
        loader: 'sasslint'
      },
      {
        test: /\.html$/,
        exclude: /node_modules/,
        loader: 'htmlhint-loader'
      }
    ];

**Comment by jeffling** [comment]
@jogjayr  It's possible that ts-loader already does some transformation that can confuse ng-annotate. When you use ng-annotate-loader did you put it before or after ts-loader? 

thanks for all your help :)

**Comment by cgatian** [comment]
Whats this `sourceMap : true` option do?  Im not setting that in my config.

**Comment by cgatian** [comment]
Wow, seemed to actually create the proper source maps when I enabled that option.  How is that not in the plugin documentation :+1:

**Comment by jogjayr** [comment]
This is the relevant loader config I use when using ng-annotate-loader:

    
     {
      test: /\.ts(x?)$/,
      loader: 'ng-annotate?map=true!ts-loader'
   };

**Comment by jeffling** [comment]
Initial issue solved through using `sourceMap : true`, so closing.
