### ISSUE TITLE
Fails to inject in directives 

### ISSUE THREAD

**Issue by KhaledMohamedP** [jeffling/ng-annotate-webpack-plugin#19]
In my current setup it fails to do the injection inside directives. Anyone else running into the same issue?

``` js
app.directive('someDirective', someDirective);

function someDirective() {
    var directive = {
        ...
         // I have to inject `$scope` manually in order for my to get it to work 
        controller: ['$scope', someDirectiveController], 
    };

    return directive;

    function someDirectiveController($scope) {

   }
}
```

BTW 

this is my simple setting for the plugin 

`new ngAnnotatePlugin({ add: true })`

**Comment by jeffling** [comment]
We are using a more current version of ngannotate now. Perhaps this could work for you.

**Comment by KhaledMohamedP** [comment]
unfortunately this still exist with the latest code ref: `0.2.0`

**Comment by jeffling** [comment]
Have you tried running ng-annotate directly on your file?
