### ISSUE TITLE
webpack4 support?

### ISSUE THREAD

**Issue by leftstick** [jeffling/ng-annotate-webpack-plugin#23]
Will you release the `webpack4` support? I am waiting for it, thanks

**Comment by kamilbrk** [comment]
This helps: `yarn add --dev "jeffling/ng-annotate-webpack-plugin#master"`

**Comment by jeffling** [comment]
Hey @leftstick, I will do a release. the code is already in

**Comment by leftstick** [comment]
nice, thanks both of you. Looking forward the new release

**Comment by jeffling** [comment]
@leftstick 0.3.0 should have the updated changes!
