### ISSUE TITLE
Version 0.3.0

### ISSUE THREAD

**Issue by rmngrc** [jeffling/ng-annotate-webpack-plugin#26]
Thanks for this plugin, I'm using it in an angularjs webapp that we are migrating to webpack in our intent to modernise it.

While having a look, I've spotted that in the git tag and in the package.json you have different version numbers. Can you publish the latest version please?

**Comment by lapo-luchini** [comment]
It lacks a tag but commit cbfe426df693711756e9e497a910e7b107b4708c seems to be the one you're looking for.

**Comment by jeffling** [comment]
Thanks! I've created a tag.
