### ISSUE TITLE
Explicit notation not working /* @ngInject */

### ISSUE THREAD

**Issue by otake** [jeffling/ng-annotate-webpack-plugin#3]
I can't get the @ngInject notation to work in any of my bundled files. When I run ng-annotate on the file manually, it seems to work fine. Any reason this wouldn't be working?

I've tried a few different ways:

    /* @ngInject */
    function myFunc() {}

    var myFunc = /* @ngInject */ function() {};

**Comment by jeffling** [comment]
@otake do you still have an issue?
